on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  build:
    name: "Build packages"
    strategy:
      matrix:
        os:
          - "windows-latest"
          - "ubuntu-latest"
          #- "macos-latest"
        dotnet:
          - "8.0"
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Setup .NET"
        uses: "actions/setup-dotnet@v4"
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: "Publish binary"
        run: "dotnet publish"
      - name: "Get build environment info"
        id: build-env-info
        shell: bash
        run: |
          # machine=x86_64
          python -c 'import platform;print("machine={}".format(platform.machine()))' | tee -a "$GITHUB_OUTPUT"
          # system=ubuntu
          echo system=${{ matrix.os }} | cut -d - -f 1 | tee -a "$GITHUB_OUTPUT"

      - name: "Construct files"
        run: |
          cp -r E5Renewer/bin/Release/net${{ matrix.dotnet }}/publish dist
          mkdir -p dist/modules
          cp -r E5Renewer.Modules.TomlParser/bin/Release/net${{ matrix.dotnet }}/publish dist/modules/E5Renewer.Modules.TomlParser
          cp -r E5Renewer.Modules.YamlParser/bin/Release/net${{ matrix.dotnet }}/publish dist/modules/E5Renewer.Modules.YamlParser
        
      - name: "Create archive"
        run: "7z a E5Renewer-${{ steps.build-env-info.outputs.system }}-${{ steps.build-env-info.outputs.machine }}.7z ./dist/*"
      - name: "Upload archive"
        uses: "actions/upload-artifact@v4"
        with:
          name: "E5Renewer-${{ steps.build-env-info.outputs.system }}-${{ steps.build-env-info.outputs.machine }}"
          path: "E5Renewer-${{ steps.build-env-info.outputs.system }}-${{ steps.build-env-info.outputs.machine }}.7z"

  release:
    name: "Upload release"
    runs-on: "ubuntu-latest"
    needs: "build"
    permissions:
      contents: "write"
    steps:
      - name: "Download archive"
        uses: "actions/download-artifact@v4"
      - name: "Create release"
        uses: "softprops/action-gh-release@v2"
        with:
          files: "**/E5Renewer-*.7z"
          generate_release_notes: true
          fail_on_unmatched_files: true
