on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  build:
    name: "Build packages"
    strategy:
      matrix:
        os:
          - "windows-latest"
          - "ubuntu-latest"
          - "macos-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Setup .NET"
        uses: "actions/setup-dotnet@v4"
        with:
          dotnet-version: '8'
      - name: "Publish binary"
        run: "dotnet publish ./E5Renewer --output dist"
      - name: "Get build environment info"
        id: build-env-info
        run: |
          # machine=x86_64
          python -c 'import platform;print("machine={}".format(platform.machine()))' >> $GITHUB_OUTPUT
          # system=ubuntu
          echo system=${{ matrix.os }} | cut -d - -f 1 >> $GITHUB_OUTPUT
        
      - name: "Create archive"
        run: "7z a E5Renewer-${{ steps.build-env-info.system }}-${{ steps.build-env-info.machine }}.7z dist/*"
      - name: "Upload archive"
        uses: "actions/upload-artifact@v4"
        with:
          name: "E5Renewer-${{ steps.build-env-info.system }}-${{ steps.build-env-info.machine }}"
          path: "E5Renewer-${{ steps.build-env-info.system }}-${{ steps.build-env-info.machine }}.7z"

  release:
    name: "Upload release"
    runs-on: "ubuntu-latest"
    needs: "build"
    steps:
      - name: "Download archive"
        uses: "actions/download-artifact@v4"
      - name: "Create release"
        uses: "softprops/action-gh-release@v2"
        with:
          files: "E5Renewer-*.7z"
          generate_release_notes: true
