name: "Run tests"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  test:
    name: "Run tests"
    strategy:
      matrix:
        os:
          - "windows-latest"
          - "ubuntu-latest"
          - "macos-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Fix long path on windows"
        if: matrix.os == 'windows-latest'
        run: "git config --system core.longpaths true"
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Setup dotnet"
        uses: "actions/setup-dotnet@v4"
        with:
          dotnet-version: '8'
      - name: "Check whitespace"
        run: "dotnet format whitespace --verify-no-changes"
      - name: "Check style"
        run: 'dotnet format style --verify-no-changes'
      - name: "Run test"
        run: 'dotnet test --collect "XPlat Code Coverage"'
